### ISSUE TITLE
missing your `findItemsOver` function

### ISSUE THREAD

**Issue by avermeulen** [GarethW1994/practical_objects#1]
@GarethW1994 I don't see your `findItemsOver` function in github. Can you please add it.

**Comment by williamsgareth** [comment]
It is on github in the 'findItemsOver20.js' file. I added the 20 at the in naming my function

**Comment by avermeulen** [comment]
@GarethW1994 then you are missing `findItemsOver20` ;-) 

Please make sure both functions are there and each one in it's own file.

**Comment by williamsgareth** [comment]
Okay I see, yes. Is it fine if I submit the other one first thing tomorrow morning?

**Comment by avermeulen** [comment]
Yeah no rush!

**Comment by williamsgareth** [comment]
Perfect . Thanks Andre.
